name: github workflow test case
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Nodejs
        uses: actions/setup-node@v1
      - name: Run test
        run: npm test